"""Fund economics for a receivables-backed private credit strategy."""

from __future__ import annotations

from dataclasses import dataclass


def _validate_non_negative(value: float, name: str) -> None:
    """Validate that a numeric assumption is not negative."""
    if value < 0:
        raise ValueError(f"{name} must be greater than or equal to zero.")


@dataclass(frozen=True, slots=True)
class Fund:
    """Economic assumptions for a receivables-backed credit fund.

    Attributes:
        portfolio_size: Total receivables exposure.
        annual_yield: Annual asset yield as a decimal.
        funding_cost: Annual cost of debt or warehouse financing as a decimal.
        management_fee: Annual management fee as a decimal of portfolio size.
    """

    portfolio_size: float
    annual_yield: float
    funding_cost: float
    management_fee: float

    def __post_init__(self) -> None:
        """Validate fund economics inputs."""
        _validate_non_negative(self.portfolio_size, "portfolio_size")
        _validate_non_negative(self.annual_yield, "annual_yield")
        _validate_non_negative(self.funding_cost, "funding_cost")
        _validate_non_negative(self.management_fee, "management_fee")

    def gross_income(self) -> float:
        """Return annual gross income generated by receivables."""
        return float(self.portfolio_size * self.annual_yield)

    def funding_expense(self) -> float:
        """Return annual expense paid to fund the portfolio."""
        return float(self.portfolio_size * self.funding_cost)

    def management_expense(self) -> float:
        """Return annual management fee expense."""
        return float(self.portfolio_size * self.management_fee)

    def net_profit(self, expected_loss: float) -> float:
        """Return net profit after funding, fees, and expected credit loss."""
        _validate_non_negative(expected_loss, "expected_loss")
        return float(
            self.gross_income()
            - self.funding_expense()
            - self.management_expense()
            - expected_loss
        )
